### ISSUE TITLE
Missing dependency for apk module

### ISSUE THREAD

**Issue by FafnerKeyZee** [certsocietegenerale/fame_modules#1]
When looking at my log, I got the following message:
2017-03-23 18:08: warning: apk: z3core: missing dependency: elftools

But when running in console the following code, I got the expected result:
>>> try:
...     from elftools.elf.elffile import ELFFile
...     HAVE_ELFTOOLS = True
... except ImportError:
...     HAVE_ELFTOOLS = False
... 
>>> if HAVE_ELFTOOLS:
...   print "ok"
... 
ok
>>> 

Any idea about bad/missing file ?

**Comment by gaelmuller** [comment]
I fixed this in e0f4c2046bd9cc5bf13ec9f11a5f56b28b53a388.

This should be OK after an update of the community repository (click on Update in the Configurations page, and wait for 1 minute or so for the worker to restart).

Could you confirm this fixes your problem ?

**Comment by FafnerKeyZee** [comment]
It's fixed, thanks for it :)
