### ISSUE TITLE
Invalid API endpoint used in get_memory_dump()

### ISSUE THREAD

**Issue by fakhrizulkifli** [certsocietegenerale/fame_modules#12]
```
        # Get back memory dump
        self.get_memory_dump()

     ...snip...

    def get_memory_dump(self):
        url = urljoin(self.web_endpoint, '/full_memory/{0}/'.format(self.task_id))
        response = requests.get(url, stream=True)

        self.register_response_as('memory_dump', response)

    def register_response_as(self, type, response, zipped=False):
        if response.status_code != 200:
            self.log('error', 'could not find {0} for task id {1}'.format(type, self.task_id))
        else:
            tmpdir = tempdir()
            filename = os.path.join(tmpdir, 'cuckoo_response')
            f = open(filename, "wb")

            for chunk in response.iter_content(1024):
                f.write(chunk)

            f.close()
            self.register_files(type, filename)
```

Wrong API endpoint used in `get_memory_dump()`. It should be `/memory/get/<id>/<number>`. Either comment out `self.get_memory_dump()` or first list out the available memory dump `/memory/list/<id>` and then loop all the output to `/memory/get/<id>/<loop>`.

**Comment by gaelmuller** [comment]
Did you try it ?

It works in my tests. What we are trying to do is retrieve the full memory dump. If my understanding is correct, the endpoint you are referring to is to retrieve the memory dump of a single process.

**Comment by fakhrizulkifli** [comment]
Disabling the get_memory_dump() is working fine. The problem is there is no full memory API endpoint available.

**Comment by gaelmuller** [comment]
The endpoint exists, I think that the issue is that you do not have full memory dump enabled on your Cuckoo instance.

I will let this issue open for now so that we better handle errors when a full memory dump is not available.
