### ISSUE TITLE
Slack module: Original URL becomes clickable

### ISSUE THREAD

**Issue by jcngodaddy** [certsocietegenerale/fame_modules#17]
This isn't so much a bug as a problem introduced by Slack.  If something LOOKS like a URL to Slack, even though you haven't flagged it as such, it tries to be helpful and make it clickable.  
Most notably, after a URL analysis, the original suspect URL becomes clickable in Slack.
As a workaround, I changed line 41 from 

string = "Just finished analysis on {0}\n".format(', '.join(analysis._file['names']))

to 

string = "Just finished analysis on {0}\n".format(', '.join(analysis._file['names']).replace('http', 'hxxp'))

The link is STILL clickable, but the worst you get (Chrome in this case) just Google searches the  hxxp 'URL'.  
Not the most elegant solution, but it works for us.

**Comment by gaelmuller** [comment]
This was fixed
