### ISSUE TITLE
Cant update community repo (this one)

### ISSUE THREAD

**Issue by Sandra-UwU-neko** [certsocietegenerale/fame_modules#38]
getting 
`Could not update repository.
invalid syntax (rarfile.py, line 811)` // via web panel 
followed this instructions [https://fame.readthedocs.io/en/latest/installation.html#](url)

![image](https://user-images.githubusercontent.com/23656101/96512009-29a87b80-1260-11eb-979a-2f9edeff780b.png)

**Comment by gaelmuller** [comment]
This should be fixed now that FAME is using Python 3
