### ISSUE TITLE
cuckoo's module typo ?

### ISSUE THREAD

**Issue by FafnerKeyZee** [certsocietegenerale/fame_modules#4]
Perhaps a small typo for the IOCs reporting:
```
    def process_report(self):
        url = self.web_base_url + '/api/tasks/get/iocs/{0}'.format(self.task_id)
        ....
```
Should be :
```
    def process_report(self):
        url = self.web_base_url + '/tasks/get/iocs/{0}'.format(self.task_id)
        ....
```
 Or I do not use the right cuckoo's version ?

**Comment by gaelmuller** [comment]
What version are you using. The only supported version at the moment is the cuckoo_modified fork (https://github.com/spender-sandbox/cuckoo-modified).

**Comment by FafnerKeyZee** [comment]
So it could be:
`tasks/get/iocs/{0}`
not:
`/tasks/get/iocs/{0}`
https://github.com/spender-sandbox/cuckoo-modified/blob/master/web/api/urls.py#L27

**Comment by gaelmuller** [comment]
Not sure what you are saying. The ``/`` is needed with the current code version because there is none at the end of ``self.web_base_url``:

```
self.base_url = 'http://{0}:{1}'.format(self.host, self.api_port)
self.web_base_url = 'http://{0}:{1}'.format(self.host, self.web_port)
```

Did you modify these lines in order to handle HTTPS ?

**Comment by FafnerKeyZee** [comment]
oops sorry
`/tasks/get/iocs/{0}`
not 
`/api/tasks/get/iocs/{0}'` 
Misstape from my side .]

**Comment by gaelmuller** [comment]
Did you try it ? The correct URL is the one used in the code (``/api/tasks/get/iocs/{0}``)

**Comment by xme** [comment]
Is this error message related to my Cuckoo version? (cuckoo 2.0-rc)

2017-04-01 18:57:05,439 [lib.cuckoo.core.scheduler] ERROR: Cannot acquire machine: No machines match selection criteria.

/x

**Comment by FafnerKeyZee** [comment]
Sorry for late answer;

@gaelmuller Ok, i've modified this version, that's why I have this error.
@xme Did you had the right tag to you VM configuration ? 'internet_access'

**Comment by xme** [comment]
Stupid me... Indeed! Fixed and working.
I had to make minor changes to the module because I'm using Cuckoo 2.0... (don't blame me :-) )

**Comment by gaelmuller** [comment]
@xme: I did not have the chance to test the module against the non-forked version of Cuckoo but was meaning to. What version are you using ? The official release or the package branch ?

I would like to have a working version for all Cuckoos by modifying the current module or providing another module if they are too different. Could you share your changes ?

**Comment by xme** [comment]
It seems that they are very different... I'm using 2.0-RC2.
I'm still trying to get a working module. I'll share if I got a working one.

**Comment by gaelmuller** [comment]
Closing this since support for Cuckoo 2 has its own issue.
