### ISSUE TITLE
Python 3 port

### ISSUE THREAD

**Issue by gaelmuller** [certsocietegenerale/fame_modules#40]
I have started migrating modules to Python 3 in the `python3` branch. I am also taking this opportunity to update and fix dependencies in the `requirements.txt` files so that modules do not stop working when dependencies are updated.

We will be using this issue to track modules that were successfully migrated & tested to be working:

- [x] ./preloading/virustotal_download
- [x] ./virtualization/vboxmanage
- [x] ./virtualization/kvm
- [x] ./threat_intelligence/yeti
- [x] ./threat_intelligence/google_safe_browsing
- [x] ./threat_intelligence/urlhaus
- [x] ./processing/cuckoo_modified
- [x] ./processing/joe/joe.py
- [x] ./processing/pdf
- [x] ./processing/malware_config/marcher_config
- [X] ./processing/apk
- [x] ./processing/zip
- [x] ~~./processing/bamfdetect~~
- [x] ./processing/cutthecrap
- [x] ./processing/exiftool
- [x] ./processing/vol
- [x] ./processing/url_preview
- [x] ./processing/extract
- [x] ./processing/msg_extractor
- [x] ./processing/cuckoo
- [x] ./processing/email_headers
- [x] ./processing/ratdecoders
- [x] ./processing/url_download
- [x] ./processing/virustotal
- [x] ./processing/xlmdeobfuscator
- [x] ./processing/office_password
- [x] ~~./processing/apk_verification~~
- [x] ./processing/mem_yara
- [x] ./processing/office_macros
- [x] ./processing/document_preview
- [x] ./processing/eml
- [x] ./antivirus/symantec
- [x] ./antivirus/mail/sophos
- [x] ./antivirus/mail/mcafee
- [x] ./reporting/mattermost
- [x] ./reporting/slack

Some modules will probably be deleted as they cannot be easily ported to Python 3 or are no longer relevant.

**Comment by lucebac** [comment]
As far as I am aware of, the following modules are already working in python 3 (in order of appearance in your list):
* kvm
* yeti
* zip
* exiftool
* url_preview
* document_preview
