### ISSUE TITLE
flare_capa exception error

### ISSUE THREAD

**Issue by phate1** [certsocietegenerale/fame_modules#68]
Hey, quick note I noticed flare_capa crashes out when it tries to raise an exception. looks like self is incorrectly being passed e.g here:

`raise ModuleExecutionError(self, 'Could not run capa on target with error: ' + str(error))`

should be:

`raise ModuleExecutionError('Could not run capa on target with error: ' + str(error))`

**Comment by Augustin-FL** [comment]
Hi,

Thanks for the PR !

Quick question before performing a deeper review : why do you say there is an error here?

I mean, If i understand correctly `ModuleExecutionError` is supposed [to take 2 arguments](https://github.com/certsocietegenerale/fame/blob/master/fame/common/exceptions.py#L2-L4) (module & description)?

**Comment by Augustin-FL** [comment]
Fixed by #69
