### ISSUE TITLE
Support for Cuckoo 2.0?

### ISSUE THREAD

**Issue by xme** [certsocietegenerale/fame_modules#7]
Hi *,

I started to fix the cuckoo-modified module to work submit files to a "regular" Cuckoo instance. But now, I'm facing more issue while getting reports from the completed analysis...
I can't deploy right now Cuckoo-modified (which looks much better I agree). So, two questions:
1. Is there a support for Cuckoo in the pipe? Is somebody working on this?
2. Is there an easy way to move from Cuckoo to Cuckoo-modified? (a good recipe / howto somewhere?)

/x

**Comment by gaelmuller** [comment]
Note that we didn't say cuckoo-modified was better 😉

1. Support for the latest version of Cuckoo (the package branch) is on my "things I would like to do eventually" list, but I haven't started anything and am not aware of anyone who did, except from you.
2. Not sure this is what I would recommend, but if you want to do it, it should not be too difficult. Install the modified version, copy your config files and debug 😄
