### ISSUE TITLE
YARA: internal fatal error?

### ISSUE THREAD

**Issue by xme** [certsocietegenerale/fame_modules#8]
I loaded a bunch of YARA rules and added them using "include".
When I try them from the CLI (same set of rules), it works (with of course warnings) but the worker is not able to use/compile them and returns:

[2017-04-07 07:42:34,355: ERROR/PoolWorker-6] Cannot compile rules: /opt/fame/storage/rules/malware/MALW_AdGholas.yar(80): internal fatal error

Any idea?

**Comment by gaelmuller** [comment]
I can confirm that the use of "include" is supported.

The rules compilation is done directly by volatility. What happens if you try to run manually the yarascan volatility module with your rules ?

**Comment by xme** [comment]
I finally managed to get it work by removing some rules... I've now a stable set of rules.
Tx! I did not investigate deeper why they returned an error...
