### ISSUE TITLE
update cuckoo_modified module for new repo

### ISSUE THREAD

**Issue by 53BStsttr6EDff** [certsocietegenerale/fame_modules#9]
spender-sandbox cuckoo-modified is no longer maintained according to https://github.com/spender-sandbox/cuckoo-modified/issues/445. In the discussion doomedraven volunteered to keep it moving here https://github.com/doomedraven/cuckoo-modified 

Should be just a simple change to point to new repo?

**Comment by gaelmuller** [comment]
Are you simply referring to the link in the README ?

**Comment by 53BStsttr6EDff** [comment]
Yes, and I'm also referring to migrating the cuckoo_modified module to use the new active repo.
