### ISSUE TITLE
Yeti module is outdated. Best upgrade strategies?

### ISSUE THREAD

**Issue by tomchop** [certsocietegenerale/fame_modules#94]
Hello!

The yeti module at https://github.com/certsocietegenerale/fame_modules/blob/master/threat_intelligence/yeti.py#L11 is outdated and only works on yeti v1.x, which is no longer maintained.

What's the best way to upgrade the compatibility to the latest version? Would you prefer updating this plugin or creating a new one (to ensure backwards compatibility for people still using yeti 1.x)

**Comment by certsocietegenerale** [comment]
Hello @tomchop 

Thanks for the heads-up! We are looking into it.

**Comment by tomchop** [comment]
Amazing, thank you so much for looking into this!

**Comment by tomchop** [comment]
The last release of Yeti (2.1.0) introduces some breaking changes in the way authentication is handled. PTAL at https://yeti-platform.io/docs/api/#authentication to see how to fix this (I will try sending a PR later this week if I have time)
